app:
  version: "stable"
  oldVersion: null

image:
  repository: stakkato95/microservice-infrastructure-backend-1
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  http:
    name: http
    port: 80
