app:
  version: "stable"
  oldVersion: null

image:
  repository: stakkato95/microservice-infrastructure-middle
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  http:
    name: http
    port: 80

release:
  weight:
    old: 90
    new: 10